[crd2pulumi] Generate multiple languages, output dirs, and YAMLS at once
pulumi/pulumi-kubernetes pull request #1289
Opened 2020-09-04 11:03 UTC by albert-zhong

Mostly some refactoring so that crd2pulumi can handle multiple YAML files and output to multiple languages (with CLI flags for specific folder paths for each) at once. With these additions, auto-generating the Pulumi libraries should be pretty straightforward, and done solely through the CLI.

2020-09-04 16:41 UTC, lblackstone requested changes

2020-09-04 21:00 UTC, albert-zhong commented on provider/cmd/crd2pulumi/gen/generate.go
> +// exists. If true, then the first outpath that already exists is also returned.
Yeah that would be more helpful for the user--I'll do that instead

2020-09-08 19:26 UTC, lblackstone commented on provider/cmd/crd2pulumi/gen/generate.go
> +var Version = "1.0.2"
```suggestion
var Version
```

This should always be set by the linker. If it's important to any of the internal logic, you should assert that it's set.

2020-09-08 19:26 UTC, lblackstone commented on provider/cmd/crd2pulumi/gen/generate.go
> +	var pathsThatAlreadyExist []string
nit: I'd call this `existingPaths`

2020-09-08 19:39 UTC, lblackstone approved these changes

2020-09-08 22:00 UTC, merged