fix: include namespace in renderedYaml filename
pulumi/pulumi-kubernetes pull request #1429
Opened 2021-01-18 18:53 UTC by rawkode

This fixes a problem when resources have the same name/kind, but live in different namespaces. This caused the first file written to be overwritten by the later resources.

2021-01-18 18:57 UTC, rawkode commented
@lblackstone I'm not sure if `GetNamespace()` will work on resources without a namespace. I'm going to run some tests now :)

2021-01-18 19:03 UTC, rawkode commented
The test that failed seems unrelated 👍

2021-01-19 23:02 UTC, lblackstone commented
/run-acceptance-tests

2021-01-19 23:12 UTC, lblackstone requested changes
Thanks for the PR! 

I do have a couple concerns about this change so far:

1. While changing the name does resolve the bug, it also would rename every generated resource YAML, which might break users' existing workflows. Adding the namespace is a good way to disambiguate, but it would be ideal if we could leave existing stacks alone. I'm not sure off the top of my head how easy that would be to check.
2. `GetNamespace()` will return `""` for the default namespace, so it would be better to format the string to avoid the extra `-` in that case. e.g. `pod-foo` rather than `pod--foo`.

2021-01-19 23:38 UTC, rawkode commented
@lblackstone With regards to issue 1 - I don't think that's a problem. Anyone generating the YAML will be using `kubectl` to apply and the filenames will be irrelevant. The directories created won't be modified, which I believe is safe to assume that's as close to coupling a consumer to `renderToYaml` may get. IMO.

Happy to implement issue 2 if you're happy to proceed on the above hypothesis.

Option 3 could be to add another option to the provider config to tweak the filenames, but I don't think that would be used really?

2021-01-20 00:05 UTC, lblackstone commented
> Anyone generating the YAML will be using `kubectl` to apply and the filenames will be irrelevant. The directories created won't be modified, which I believe is safe to assume that's as close to coupling a consumer to `renderToYaml` may get...Happy to implement issue 2 if you're happy to proceed on the above hypothesis.

Yeah, that's probably a reasonable assumption. Let's proceed with this change, and I'll bump the minor version of the next release since it's technically a breaking change.

2021-01-20 00:06 UTC, lblackstone commented on CHANGELOG.md
> +- Fix bug where rendering manifests results in files being overwritten by subsequent resources with the same kind and name, but different namespace
```suggestion
-  Fix bug where rendering manifests results in files being overwritten by subsequent resources with the same kind and name, but different namespace (https://github.com/pulumi/pulumi-kubernetes/pull/1429)
```

2021-02-25 23:30 UTC, leezen commented
@rawkode Just checking in to see if you plan to come back to this. Thanks!

2021-02-25 23:32 UTC, rawkode commented
> @rawkode Just checking in to see if you plan to come back to this. Thanks!

The last message from @lblackstone said they where happy to go with it as it is, under our assumptions. 

I was just waiting for this to be merged.

2021-02-25 23:35 UTC, lblackstone commented
Oh, sorry for the confusion. There's still one point of feedback to address, and then we can merge.

> GetNamespace() will return "" for the default namespace, so it would be better to format the string to avoid the extra - in that case. e.g. pod-foo rather than pod--foo.

2021-02-26 17:04 UTC, lblackstone commented
/run-acceptance-tests

2021-02-26 17:06 UTC, lblackstone approved these changes

2021-02-26 17:34 UTC, merged

2021-02-26 17:34 UTC, lblackstone commented
Thanks for the PR!