Automatically fall back to CSA mode for preview if SSA fails
pulumi/pulumi-kubernetes pull request #2419
Opened 2023-05-18 21:47 UTC by lblackstone

### Proposed changes
Server-side apply previews currently require "patch" permission to run. For cases where the user doesn't have permission to perform a "patch" operation, attempt a graceful fallback to Client-side preview. The Client-side preview may not be 100% accurate, but is preferable to failing with a permission error.

### Related issues (optional)
Fix https://github.com/pulumi/pulumi-kubernetes/issues/2411

2023-05-22 21:32 UTC, lblackstone commented
Without the provider change, the test fails with the following error:
```
error: configmaps "foo" is forbidden: User "system:serviceaccount:kube-system:kubeconfig-sa" cannot delete resource "configmaps" in API group "" in the namespace "test-30a036a4"
```

2023-05-23 15:41 UTC, kpitzen approved these changes

2023-05-23 16:34 UTC, rquitales requested changes
Mostly LGTM! Just 1 comment to address.

2023-05-23 18:06 UTC, lblackstone commented on tests/sdk/nodejs/nodejs_test.go
> +	// Clean up kubeconfig user.
Yes, great point!

2023-05-23 19:19 UTC, rquitales approved these changes

2023-05-23 19:42 UTC, merged

2023-08-21 19:08 UTC, sam-utila commented
Great job, just needed it