Add another csa to ssa test
pulumi/pulumi-kubernetes pull request #2472
Opened 2023-06-26 18:56 UTC by rquitales

WIP

2023-06-26 23:54 UTC, rquitales commented
Tested the changes against current `master` branch (ie. the v3 releases), and tests fail which is expected.

2023-06-27 00:23 UTC, lblackstone requested changes
One test update, but LGTM otherwise!

2023-06-27 00:23 UTC, lblackstone commented on tests/sdk/go/switch-ssa-delete-container/step1/main.go
> +				Namespace: pulumi.String("default"),
We should put the Deployment in a new Namespace to avoid possible resource conflicts between parallel tests on the shared CI cluster.

2023-06-27 01:44 UTC, lblackstone commented on tests/sdk/go/switch-ssa-delete-container/step2/main.go
> +			EnableServerSideApply: pulumi.BoolPtr(false),
Did you mean to flip the polarity here? It looks like both steps are CSA now.

2023-06-27 17:35 UTC, lblackstone approved these changes

2023-06-27 18:10 UTC, merged