Helm Release: kubeVersion/apiVersions properties
pulumi/pulumi-kubernetes pull request #2654
Opened 2023-11-04 18:15 UTC by EronWright

### Proposed changes

This PR is a follow-up to https://github.com/pulumi/pulumi-kubernetes/pull/2593 to add `kubeVersion` and `apiVersions` to the Helm Release object.

Note that the properties are applicable only during templating; Helm seems to always use server detection in the actual install/upgrade operation.

A possible enhancement to be considered is to automatically incorporate the CRD information into the `Capabiltiies.APIVersions` that are used during templating. Imagine that the chart includes some CRDs that aren't yet installed on the server, what is the templating behavior?  Helm itself doesn't seem to solve it.

Fixes: https://github.com/pulumi/pulumi-kubernetes/issues/2563

### Related issues (optional)

2023-11-13 22:01 UTC, EronWright commented
@rquitales do you happen to know the meaning of this block, and whether the new properties should be listed there?
https://github.com/pulumi/pulumi-kubernetes/pull/2654/files#diff-81d686e8bffdb383464867f6848af2152fe29b75fd70da67eaf1e8603d4e4207L689-L704

2023-11-14 00:38 UTC, rquitales commented
> @rquitales do you happen to know the meaning of this block, and whether the new properties should be listed there? https://github.com/pulumi/pulumi-kubernetes/pull/2654/files#diff-81d686e8bffdb383464867f6848af2152fe29b75fd70da67eaf1e8603d4e4207L689-L704

This is a NodeJS specific codegen extension to mark the output as a required output. Looking at all the other types, we should indeed be adding new properties here.

2023-11-14 00:41 UTC, rquitales requested changes
Would be great if we could have some tests for these changes as well. Thanks.

2023-11-20 16:35 UTC, EronWright commented
Am closing as obsoleted by #2649; the `Release` resource won't do templating, and the overrides weren't used by Helm in the actual install/upgrade procedure anyway.

2023-11-20 16:35 UTC, closed without merging